# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zadanie4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 494)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 30, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 120, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 150, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 180, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 210, 461, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.amp_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.amp_1.setGeometry(QtCore.QRect(320, 120, 141, 22))
        self.amp_1.setObjectName("amp_1")
        self.amp_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.amp_2.setGeometry(QtCore.QRect(510, 120, 141, 22))
        self.amp_2.setObjectName("amp_2")
        self.pha_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.pha_1.setGeometry(QtCore.QRect(320, 180, 141, 22))
        self.pha_1.setObjectName("pha_1")
        self.fre_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.fre_2.setGeometry(QtCore.QRect(510, 150, 141, 22))
        self.fre_2.setObjectName("fre_2")
        self.fre_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.fre_1.setGeometry(QtCore.QRect(320, 150, 141, 22))
        self.fre_1.setObjectName("fre_1")
        self.pha_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.pha_2.setGeometry(QtCore.QRect(510, 180, 141, 22))
        self.pha_2.setObjectName("pha_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Интенрференция"))
        self.label_2.setText(_translate("MainWindow", "Первая волна"))
        self.label_3.setText(_translate("MainWindow", "Амплинуда, м"))
        self.label_4.setText(_translate("MainWindow", "Частота, Гц"))
        self.label_5.setText(_translate("MainWindow", "фаза"))
        self.label_6.setText(_translate("MainWindow", "Вторая волна"))
        self.pushButton.setText(_translate("MainWindow", "Построить графики"))
